openapi: 3.0.0
info:
  version: 1.0.0
  title: Férj/Feleség kölcsönző Szerver API Dokumentáció
  description: A Férj/Feleség kölcsönző végpontjainak részletes leírása és használata
servers:
  - url: http://localhost:3000
paths:
  /users:
    get: 
      description: Returns a list of users
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Success
          content: 
            application/json:
              schema:
                type: array
                items:
                  $ref: ''
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    User:
      type: object
      required: 
        - user_name
        - first_name
        - last_name
        - gender
        - birth_date
        - address
        - email
        - mobil_number
        - password
        - role
      properties:
        user_name: 
          type: string
        first_name: 
          type: string
        last_name: 
          type: string
        gender:
          type: string
        